### ISSUE TITLE
not a member of ‘pmt’

### ISSUE THREAD

**Issue by cyberxml** [hui811116/gr-gadget#1]
Attempting to build gr-gadget in Ubuntu 14.0.4LTS virtual machine

OS in VM
```
cat /etc/issue
Ubuntu 14.04.6 LTS
```
GNU Radio Companion installed via apt
```
gnuradio-companion --version
GNU Radio Companion 3.7.2.1
```
Modification to CMakeLists.txt
```
 list(APPEND CMAKE_MODULE_PATH "/usr/lib/x86_64-linux-gnu/cmake/gnuradio")
```
Build commands
```
mkdir build
cd build
cmake ..
make
```
Compile error
```
root@vagrant-ubuntu-trusty-64:/opt/gr-gadget/build# make
Scanning dependencies of target gnuradio-gadget
[  5%] Building CXX object lib/CMakeFiles/gnuradio-gadget.dir/payload_sink.cc.o
/opt/gr-gadget/lib/payload_sink.cc: In member function ‘void gr::gadget::payload_sink_impl::msg_in(pmt::pmt_t)’:
/opt/gr-gadget/lib/payload_sink.cc:112:17: error: ‘to_float’ is not a member of ‘pmt’
           pwr = pmt::to_float(pmt::dict_ref(k,pmt::intern("pwr"),pmt::from_float(0)));
                 ^
/opt/gr-gadget/lib/payload_sink.cc:112:66: error: ‘from_float’ is not a member of ‘pmt’
           pwr = pmt::to_float(pmt::dict_ref(k,pmt::intern("pwr"),pmt::from_float(0)));
                                                                  ^
make[2]: *** [lib/CMakeFiles/gnuradio-gadget.dir/payload_sink.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-gadget.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by cyberxml** [comment]
Documentation for 3.7.2 PMT doesn't have `pmt::to_float` or `pmt::from_float`
It does have similar double types
https://www.gnuradio.org/doc/sphinx-3.7.2/pmt/index.html

**Comment by cyberxml** [comment]
GnuRadio v 3.7.6 is the earliest version I can find which supports `pmt::to_float`
https://www.gnuradio.org/doc/doxygen-3.7.6/namespacepmt.html

**Comment by hui811116** [comment]
Correct. It seems like this issue occurs because of older version of Gnuradio.
But I believe this was not prevented from initiating a Gnuradio module then. 

If you wish to proceed with version 3.7.2, you can try changing pmt::to_float() and pmt::from_float() to:
pmt::to_double() and pmt::from_double()
but remember to recast the variable "pwr" accordingly. Thank you

https://www.gnuradio.org/doc/doxygen-3.7.2/namespacepmt.html#ad20c287c509e8470d03d1c8e97fea12d
https://www.gnuradio.org/doc/doxygen-3.7.2/namespacepmt.html#a0f58166fe9f449249f5de7dc7b3ab754

**Comment by cyberxml** [comment]
Noting that the CMakeLists.txt requires GNU Radio version 3.7.2. 
I don't know cmake well enough to know if that allows for later version

`find_package(Gnuradio "3.7.2" REQUIRED)`
